development:
  adapter: postgresql
  encoding: unicode
  database: climbing_log_book_development
  pool: 5
  username: climbing_log_book
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: climbing_log_book_test
  pool: 5
  username: climbing_log_book
  password: password1
